apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  access_key_id: "YOUR_AWS_ACCESS_KEY_ID_BASE64"
  secret_access_key: "YOUR_AWS_SECRET_ACCESS_KEY_BASE64"
  sentry_dsn: "YOUR_SENTRY_DSN_BASE64"
  redis_host: "YOUR_ELASTICACHE_REDIS_ENDPOINT_BASE64"
  database_url: "YOUR_RDS_DATABASE_URL_BASE64"
